name: Build Android

on:
  workflow_dispatch:
  push:
    branches:
      - main
    tags:
      - "v*"

jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Setup Java
        uses: actions/setup-java@v5.7.0
        with:
          distribution: temurin
          java-version: "21"

      - name: Download Ren'Py
        run: |
          wget https://www.renpy.org/dl/8.5.3/renpy-8.5.3-sdk.tar.bz2
          tar -xjf renpy-8.5.3-sdk.tar.bz2

      - name: Download RAPT
        run: |
          wget https://www.renpy.org/dl/8.5.3/renpy-8.5.3-rapt.zip
          unzip renpy-8.5.3-rapt.zip -d renpy-8.5.3-sdk

      - name: Restore Android keys
        run: |
          echo "${{ secrets.ANDROID_KEYSTORE }}" | base64 -d > android.keystore
          echo "${{ secrets.BUNDLE_KEYSTORE }}" | base64 -d > bundle.keystore

      - name: Cache Gradle
        uses: actions/cache@v5
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}
          restore-keys: |
            gradle-

      - name: Build Android APK
        run: |
          mkdir -p dist
          cd renpy-8.5.3-sdk
          ./renpy.sh launcher android_build "$GITHUB_WORKSPACE" \
            --destination "$GITHUB_WORKSPACE/dist"

      - name: Get version
        id: version
        run: |
          echo "version=$(python -c "import json; print(json.load(open('android.json'))['version'])")" >> $GITHUB_OUTPUT

      - name: Rename APK
        run: |
          VERSION=$(python -c "import json; print(json.load(open('android.json'))['version'])")
          mv dist/*.apk dist/McenahleGame-${VERSION}-android.apk

      - name: Check APK size
        run: |
          ls -lh dist
          du -sh dist/*

      - name: Upload APK
        uses: actions/upload-artifact@v7
        with:
          name: McenahleGame-${{ steps.version.outputs.version }}-android
          path: dist/*.apk

      - name: Publish Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v3
        with:
          files: dist/*.apk
