name: Build Windows

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download RenPy
        run: |
          wget https://www.renpy.org/dl/8.5.3/renpy-8.5.3-sdk.tar.bz2
          tar -xf renpy-8.5.3-sdk.tar.bz2

      - name: Build Windows
        run: |
          ./renpy-8.5.3-sdk/renpy.sh launcher distribute . --destination build

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: windows-build
          path: build/*
