name: Build Windows

on:
  workflow_dispatch:
  push:
    branches:
      - main
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Download Ren'Py
        run: |
          wget https://www.renpy.org/dl/8.5.3/renpy-8.5.3-sdk.tar.bz2
          tar -xf renpy-8.5.3-sdk.tar.bz2

      - name: Build Windows
        run: |
          cd renpy-8.5.3-sdk
          ./renpy.sh launcher distribute "$GITHUB_WORKSPACE" \
          --destination "$GITHUB_WORKSPACE/build" \
          --package pc

      - name: Upload Windows build
        uses: actions/upload-artifact@v7
        with:
          name: McenahleGame-Windows
          path: build/*

      - name: Upload Release Asset
        if: startsWith(github.ref, 'refs/tags/v')
        uses: softprops/action-gh-release@v3
        with:
          files: build/*
