name: Build Windows

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Download RenPy
        run: |
          wget https://www.renpy.org/dl/8.5.3/renpy-8.5.3-sdk.tar.bz2
          tar -xf renpy-8.5.3-sdk.tar.bz2

      - name: Build Windows
        run: |
          ./renpy-8.5.3-sdk/renpy.sh "$PWD" distribute --destination build

      - name: Upload
        uses: actions/upload-artifact@v7
        with:
          name: windows-build
          path: build/*
